# Generated by Django 6.0.6 on 2026-06-25 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_item', models.IntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('Inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.inventory')),
            ],
        ),
    ]
